(cl:in-package uav_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          INTEGRATION_TIME_US-VAL
          INTEGRATION_TIME_US
          INTEGRATED_X-VAL
          INTEGRATED_X
          INTEGRATED_Y-VAL
          INTEGRATED_Y
          INTEGRATED_XGYRO-VAL
          INTEGRATED_XGYRO
          INTEGRATED_YGYRO-VAL
          INTEGRATED_YGYRO
          INTEGRATED_ZGYRO-VAL
          INTEGRATED_ZGYRO
          TEMPERATURE-VAL
          TEMPERATURE
          QUALITY-VAL
          QUALITY
          GROUND_DISTANCE-VAL
          GROUND_DISTANCE
          TIME_DELTA_DISTANCE_US-VAL
          TIME_DELTA_DISTANCE_US
))