; Auto-generated. Do not edit!


(cl:in-package uav_msgs-msg)


;//! \htmlinclude EstUavState.msg.html

(cl:defclass <EstUavState> (roslisp-msg-protocol:ros-message)
  ((timestamp
    :reader timestamp
    :initarg :timestamp
    :type cl:real
    :initform 0)
   (state
    :reader state
    :initarg :state
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (covariance
    :reader covariance
    :initarg :covariance
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass EstUavState (<EstUavState>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EstUavState>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EstUavState)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name uav_msgs-msg:<EstUavState> is deprecated: use uav_msgs-msg:EstUavState instead.")))

(cl:ensure-generic-function 'timestamp-val :lambda-list '(m))
(cl:defmethod timestamp-val ((m <EstUavState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader uav_msgs-msg:timestamp-val is deprecated.  Use uav_msgs-msg:timestamp instead.")
  (timestamp m))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <EstUavState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader uav_msgs-msg:state-val is deprecated.  Use uav_msgs-msg:state instead.")
  (state m))

(cl:ensure-generic-function 'covariance-val :lambda-list '(m))
(cl:defmethod covariance-val ((m <EstUavState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader uav_msgs-msg:covariance-val is deprecated.  Use uav_msgs-msg:covariance instead.")
  (covariance m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<EstUavState>)))
    "Constants for message type '<EstUavState>"
  '((:IDX_ROLL . 0)
    (:IDX_PITCH . 1)
    (:IDX_YAW . 2)
    (:IDX_VEL_U . 3)
    (:IDX_VEL_V . 4)
    (:IDX_VEL_W . 5)
    (:IDX_THRUST . 6)
    (:IDX_POS_X . 7)
    (:IDX_POS_Y . 8)
    (:IDX_POS_Z . 9)
    (:IDX_DRAG_COEFF . 10))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'EstUavState)))
    "Constants for message type 'EstUavState"
  '((:IDX_ROLL . 0)
    (:IDX_PITCH . 1)
    (:IDX_YAW . 2)
    (:IDX_VEL_U . 3)
    (:IDX_VEL_V . 4)
    (:IDX_VEL_W . 5)
    (:IDX_THRUST . 6)
    (:IDX_POS_X . 7)
    (:IDX_POS_Y . 8)
    (:IDX_POS_Z . 9)
    (:IDX_DRAG_COEFF . 10))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EstUavState>) ostream)
  "Serializes a message object of type '<EstUavState>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timestamp)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timestamp) (cl:floor (cl:slot-value msg 'timestamp)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'state))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'covariance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'covariance))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EstUavState>) istream)
  "Deserializes a message object of type '<EstUavState>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timestamp) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'state) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'state)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'covariance) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'covariance)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EstUavState>)))
  "Returns string type for a message object of type '<EstUavState>"
  "uav_msgs/EstUavState")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EstUavState)))
  "Returns string type for a message object of type 'EstUavState"
  "uav_msgs/EstUavState")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EstUavState>)))
  "Returns md5sum for a message object of type '<EstUavState>"
  "884afb55d3979e06b05814ad6674c8fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EstUavState)))
  "Returns md5sum for a message object of type 'EstUavState"
  "884afb55d3979e06b05814ad6674c8fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EstUavState>)))
  "Returns full string definition for message of type '<EstUavState>"
  (cl:format cl:nil "# UavEstState.msg~%# Message describing estimated current state of the UAV~%~%# Timestamp of state estimate~%time timestamp~%~%# State vector and covariance~%float64[] state~%float64[] covariance~%~%# State field definitions~%int32 IDX_ROLL 		= 0~%int32 IDX_PITCH 	= 1~%int32 IDX_YAW 		= 2~%int32 IDX_VEL_U 	= 3~%int32 IDX_VEL_V 	= 4~%int32 IDX_VEL_W 	= 5~%int32 IDX_THRUST	= 6~%int32 IDX_POS_X		= 7~%int32 IDX_POS_Y		= 8~%int32 IDX_POS_Z		= 9~%int32 IDX_DRAG_COEFF	= 10~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EstUavState)))
  "Returns full string definition for message of type 'EstUavState"
  (cl:format cl:nil "# UavEstState.msg~%# Message describing estimated current state of the UAV~%~%# Timestamp of state estimate~%time timestamp~%~%# State vector and covariance~%float64[] state~%float64[] covariance~%~%# State field definitions~%int32 IDX_ROLL 		= 0~%int32 IDX_PITCH 	= 1~%int32 IDX_YAW 		= 2~%int32 IDX_VEL_U 	= 3~%int32 IDX_VEL_V 	= 4~%int32 IDX_VEL_W 	= 5~%int32 IDX_THRUST	= 6~%int32 IDX_POS_X		= 7~%int32 IDX_POS_Y		= 8~%int32 IDX_POS_Z		= 9~%int32 IDX_DRAG_COEFF	= 10~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EstUavState>))
  (cl:+ 0
     8
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'state) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'covariance) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EstUavState>))
  "Converts a ROS message object to a list"
  (cl:list 'EstUavState
    (cl:cons ':timestamp (timestamp msg))
    (cl:cons ':state (state msg))
    (cl:cons ':covariance (covariance msg))
))
