/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/sam/Desktop/pixhawk/src/uav-msgs/msg/EstRoombaList.msg
 *
 */


#ifndef UAV_MSGS_MESSAGE_ESTROOMBALIST_H
#define UAV_MSGS_MESSAGE_ESTROOMBALIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uav_msgs/EstRoombaState.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct EstRoombaList_
{
  typedef EstRoombaList_<ContainerAllocator> Type;

  EstRoombaList_()
    : timestamp()
    , num_tracked(0)
    , roombas()  {
    }
  EstRoombaList_(const ContainerAllocator& _alloc)
    : timestamp()
    , num_tracked(0)
    , roombas(_alloc)  {
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _num_tracked_type;
  _num_tracked_type num_tracked;

   typedef std::vector< ::uav_msgs::EstRoombaState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::uav_msgs::EstRoombaState_<ContainerAllocator> >::other >  _roombas_type;
  _roombas_type roombas;




  typedef boost::shared_ptr< ::uav_msgs::EstRoombaList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::EstRoombaList_<ContainerAllocator> const> ConstPtr;

}; // struct EstRoombaList_

typedef ::uav_msgs::EstRoombaList_<std::allocator<void> > EstRoombaList;

typedef boost::shared_ptr< ::uav_msgs::EstRoombaList > EstRoombaListPtr;
typedef boost::shared_ptr< ::uav_msgs::EstRoombaList const> EstRoombaListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::EstRoombaList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::EstRoombaList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'uav_msgs': ['/home/sam/Desktop/pixhawk/src/uav-msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::EstRoombaList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::EstRoombaList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::EstRoombaList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21f683d31466b702adba7720f61ddf8c";
  }

  static const char* value(const ::uav_msgs::EstRoombaList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21f683d31466b702ULL;
  static const uint64_t static_value2 = 0xadba7720f61ddf8cULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/EstRoombaList";
  }

  static const char* value(const ::uav_msgs::EstRoombaList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RoombaEstList.msg\n\
# Message containing list of tracked Roomba states\n\
\n\
# Timestamp of state estimate\n\
time timestamp\n\
\n\
# Number of tracked roombas\n\
int32 num_tracked\n\
\n\
EstRoombaState[] roombas\n\
\n\
================================================================================\n\
MSG: uav_msgs/EstRoombaState\n\
# RoombaEstState.msg\n\
# Message describing estimated current state of a Roomba\n\
\n\
# Timestamp of state estimate\n\
time timestamp\n\
\n\
# Roomba type specifier\n\
int32 SHEEP=1\n\
int32 OBSTACLE=5\n\
int32 type\n\
\n\
float64[] state\n\
float64[] covariance\n\
\n\
# State variable enumerations\n\
int32 IDX_POS_X		= 0\n\
int32 IDX_POS_Y		= 1\n\
int32 IDX_BEARING	= 2\n\
";
  }

  static const char* value(const ::uav_msgs::EstRoombaList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.num_tracked);
      stream.next(m.roombas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EstRoombaList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::EstRoombaList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::EstRoombaList_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "num_tracked: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_tracked);
    s << indent << "roombas[]" << std::endl;
    for (size_t i = 0; i < v.roombas.size(); ++i)
    {
      s << indent << "  roombas[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::uav_msgs::EstRoombaState_<ContainerAllocator> >::stream(s, indent + "    ", v.roombas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_ESTROOMBALIST_H
