/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/sam/Desktop/pixhawk/src/uav-msgs/msg/OpticalFlowRad.msg
 *
 */


#ifndef UAV_MSGS_MESSAGE_OPTICALFLOWRAD_H
#define UAV_MSGS_MESSAGE_OPTICALFLOWRAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct OpticalFlowRad_
{
  typedef OpticalFlowRad_<ContainerAllocator> Type;

  OpticalFlowRad_()
    : time_usec(0)
    , sensor_id(0)
    , integration_time_us(0)
    , integrated_x(0.0)
    , integrated_y(0.0)
    , integrated_xgyro(0.0)
    , integrated_ygyro(0.0)
    , integrated_zgyro(0.0)
    , temperature(0)
    , quality(0)
    , time_delta_distance_us(0)
    , distance(0.0)  {
    }
  OpticalFlowRad_(const ContainerAllocator& _alloc)
    : time_usec(0)
    , sensor_id(0)
    , integration_time_us(0)
    , integrated_x(0.0)
    , integrated_y(0.0)
    , integrated_xgyro(0.0)
    , integrated_ygyro(0.0)
    , integrated_zgyro(0.0)
    , temperature(0)
    , quality(0)
    , time_delta_distance_us(0)
    , distance(0.0)  {
    }



   typedef uint64_t _time_usec_type;
  _time_usec_type time_usec;

   typedef uint8_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef uint32_t _integration_time_us_type;
  _integration_time_us_type integration_time_us;

   typedef float _integrated_x_type;
  _integrated_x_type integrated_x;

   typedef float _integrated_y_type;
  _integrated_y_type integrated_y;

   typedef float _integrated_xgyro_type;
  _integrated_xgyro_type integrated_xgyro;

   typedef float _integrated_ygyro_type;
  _integrated_ygyro_type integrated_ygyro;

   typedef float _integrated_zgyro_type;
  _integrated_zgyro_type integrated_zgyro;

   typedef int16_t _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _quality_type;
  _quality_type quality;

   typedef uint32_t _time_delta_distance_us_type;
  _time_delta_distance_us_type time_delta_distance_us;

   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> const> ConstPtr;

}; // struct OpticalFlowRad_

typedef ::uav_msgs::OpticalFlowRad_<std::allocator<void> > OpticalFlowRad;

typedef boost::shared_ptr< ::uav_msgs::OpticalFlowRad > OpticalFlowRadPtr;
typedef boost::shared_ptr< ::uav_msgs::OpticalFlowRad const> OpticalFlowRadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::OpticalFlowRad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'uav_msgs': ['/home/sam/Desktop/pixhawk/src/uav-msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a588d39eb1ee1fc1235949376ff1c66";
  }

  static const char* value(const ::uav_msgs::OpticalFlowRad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a588d39eb1ee1fcULL;
  static const uint64_t static_value2 = 0x1235949376ff1c66ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/OpticalFlowRad";
  }

  static const char* value(const ::uav_msgs::OpticalFlowRad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# OptFlowSample.msg\n\
# Post-processed optical flow measurement\n\
\n\
# Timestamp of measurement (usec since PX4 startup)\n\
uint64 time_usec\n\
\n\
uint8 sensor_id\n\
\n\
# Integration period in usec\n\
uint32 integration_time_us	\n\
\n\
# Integrated flow\n\
float32 integrated_x\n\
float32 integrated_y\n\
\n\
# Integrated gyro roll rates for compensation\n\
float32 integrated_xgyro 	# [rad]\n\
float32 integrated_ygyro\n\
float32 integrated_zgyro\n\
\n\
# Temperature\n\
int16 temperature 			# *100 = degrees Celsius\n\
\n\
# Quality\n\
# scalar measure of flow quality [0,255]\n\
# 255 => best quality\n\
uint8 quality\n\
\n\
# Ground distance [m]\n\
uint32 time_delta_distance_us	# us since distance measurement\n\
float32 distance\n\
\n\
\n\
";
  }

  static const char* value(const ::uav_msgs::OpticalFlowRad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_usec);
      stream.next(m.sensor_id);
      stream.next(m.integration_time_us);
      stream.next(m.integrated_x);
      stream.next(m.integrated_y);
      stream.next(m.integrated_xgyro);
      stream.next(m.integrated_ygyro);
      stream.next(m.integrated_zgyro);
      stream.next(m.temperature);
      stream.next(m.quality);
      stream.next(m.time_delta_distance_us);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct OpticalFlowRad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::OpticalFlowRad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::OpticalFlowRad_<ContainerAllocator>& v)
  {
    s << indent << "time_usec: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time_usec);
    s << indent << "sensor_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "integration_time_us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.integration_time_us);
    s << indent << "integrated_x: ";
    Printer<float>::stream(s, indent + "  ", v.integrated_x);
    s << indent << "integrated_y: ";
    Printer<float>::stream(s, indent + "  ", v.integrated_y);
    s << indent << "integrated_xgyro: ";
    Printer<float>::stream(s, indent + "  ", v.integrated_xgyro);
    s << indent << "integrated_ygyro: ";
    Printer<float>::stream(s, indent + "  ", v.integrated_ygyro);
    s << indent << "integrated_zgyro: ";
    Printer<float>::stream(s, indent + "  ", v.integrated_zgyro);
    s << indent << "temperature: ";
    Printer<int16_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "quality: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "time_delta_distance_us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_delta_distance_us);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_OPTICALFLOWRAD_H
