/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/sam/Desktop/pixhawk/src/uav_msgs/msg/OpticalFlowPost.msg
 *
 */


#ifndef UAV_MSGS_MESSAGE_OPTICALFLOWPOST_H
#define UAV_MSGS_MESSAGE_OPTICALFLOWPOST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct OpticalFlowPost_
{
  typedef OpticalFlowPost_<ContainerAllocator> Type;

  OpticalFlowPost_()
    : timestamp()
    , quality(0)
    , uncertainty(0.0)
    , x_vel(0.0)
    , y_vel(0.0)  {
    }
  OpticalFlowPost_(const ContainerAllocator& _alloc)
    : timestamp()
    , quality(0)
    , uncertainty(0.0)
    , x_vel(0.0)
    , y_vel(0.0)  {
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _quality_type;
  _quality_type quality;

   typedef double _uncertainty_type;
  _uncertainty_type uncertainty;

   typedef double _x_vel_type;
  _x_vel_type x_vel;

   typedef double _y_vel_type;
  _y_vel_type y_vel;




  typedef boost::shared_ptr< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> const> ConstPtr;

}; // struct OpticalFlowPost_

typedef ::uav_msgs::OpticalFlowPost_<std::allocator<void> > OpticalFlowPost;

typedef boost::shared_ptr< ::uav_msgs::OpticalFlowPost > OpticalFlowPostPtr;
typedef boost::shared_ptr< ::uav_msgs::OpticalFlowPost const> OpticalFlowPostConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::OpticalFlowPost_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'uav_msgs': ['/home/sam/Desktop/pixhawk/src/uav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7693ea6e50aea50c4aac7307bf7713e";
  }

  static const char* value(const ::uav_msgs::OpticalFlowPost_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7693ea6e50aea50ULL;
  static const uint64_t static_value2 = 0xc4aac7307bf7713eULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/OpticalFlowPost";
  }

  static const char* value(const ::uav_msgs::OpticalFlowPost_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# OpticalFlowPost.msg\n\
# Post-processed optical flow measurement\n\
\n\
# Timestamp of measurement\n\
time timestamp\n\
\n\
# Quality\n\
# scalar measure of flow quality [0,255]\n\
# 255 => best quality\n\
int32 quality\n\
\n\
# Uncertainty\n\
# scalar measure of uncertainty in range [0,1]\n\
# 0 is most certain, 1 is least certain\n\
# calculated from quality\n\
float64 uncertainty\n\
\n\
# Velocities\n\
float64 x_vel\n\
float64 y_vel\n\
";
  }

  static const char* value(const ::uav_msgs::OpticalFlowPost_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.quality);
      stream.next(m.uncertainty);
      stream.next(m.x_vel);
      stream.next(m.y_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct OpticalFlowPost_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::OpticalFlowPost_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::OpticalFlowPost_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "quality: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quality);
    s << indent << "uncertainty: ";
    Printer<double>::stream(s, indent + "  ", v.uncertainty);
    s << indent << "x_vel: ";
    Printer<double>::stream(s, indent + "  ", v.x_vel);
    s << indent << "y_vel: ";
    Printer<double>::stream(s, indent + "  ", v.y_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_OPTICALFLOWPOST_H
