/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/sam/Desktop/pixhawk/src/uav_msgs/msg/RoombaEstState.msg
 *
 */


#ifndef UAV_MSGS_MESSAGE_ROOMBAESTSTATE_H
#define UAV_MSGS_MESSAGE_ROOMBAESTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct RoombaEstState_
{
  typedef RoombaEstState_<ContainerAllocator> Type;

  RoombaEstState_()
    : timestamp()
    , num_tracked(0)
    , type()
    , pose()
    , speed()  {
    }
  RoombaEstState_(const ContainerAllocator& _alloc)
    : timestamp()
    , num_tracked(0)
    , type(_alloc)
    , pose(_alloc)
    , speed(_alloc)  {
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _num_tracked_type;
  _num_tracked_type num_tracked;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _type_type;
  _type_type type;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _pose_type;
  _pose_type pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _speed_type;
  _speed_type speed;


    enum { SHEEP = 1 };
     enum { OBSTACLE = 5 };
 

  typedef boost::shared_ptr< ::uav_msgs::RoombaEstState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::RoombaEstState_<ContainerAllocator> const> ConstPtr;

}; // struct RoombaEstState_

typedef ::uav_msgs::RoombaEstState_<std::allocator<void> > RoombaEstState;

typedef boost::shared_ptr< ::uav_msgs::RoombaEstState > RoombaEstStatePtr;
typedef boost::shared_ptr< ::uav_msgs::RoombaEstState const> RoombaEstStateConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::RoombaEstState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::RoombaEstState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'uav_msgs': ['/home/sam/Desktop/pixhawk/src/uav_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::RoombaEstState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::RoombaEstState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::RoombaEstState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cad0d9a29bb0c082d93eb53e3d89ebd4";
  }

  static const char* value(const ::uav_msgs::RoombaEstState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcad0d9a29bb0c082ULL;
  static const uint64_t static_value2 = 0xd93eb53e3d89ebd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/RoombaEstState";
  }

  static const char* value(const ::uav_msgs::RoombaEstState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RoombaEstState.msg\n\
# Message describing estimated current state of any tracked Roombas\n\
\n\
# Timestamp of state estimate\n\
time timestamp\n\
\n\
# Number of tracked roombas\n\
int32 num_tracked\n\
\n\
# Roomba type specifier\n\
int32 SHEEP=1\n\
int32 OBSTACLE=5\n\
int32[] type\n\
\n\
# 2D Pose [m]\n\
geometry_msgs/Pose2D[] pose\n\
\n\
# Velocity [m/s]\n\
float64[] speed\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::uav_msgs::RoombaEstState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.num_tracked);
      stream.next(m.type);
      stream.next(m.pose);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RoombaEstState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::RoombaEstState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::RoombaEstState_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "num_tracked: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_tracked);
    s << indent << "type[]" << std::endl;
    for (size_t i = 0; i < v.type.size(); ++i)
    {
      s << indent << "  type[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.type[i]);
    }
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.pose[i]);
    }
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_ROOMBAESTSTATE_H
