/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/sam/Desktop/pixhawk/src/uav-msgs/msg/SimpleUavCmd.msg
 *
 */


#ifndef UAV_MSGS_MESSAGE_SIMPLEUAVCMD_H
#define UAV_MSGS_MESSAGE_SIMPLEUAVCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct SimpleUavCmd_
{
  typedef SimpleUavCmd_<ContainerAllocator> Type;

  SimpleUavCmd_()
    : x_dir(0.0)
    , y_dir(0.0)  {
    }
  SimpleUavCmd_(const ContainerAllocator& _alloc)
    : x_dir(0.0)
    , y_dir(0.0)  {
    }



   typedef double _x_dir_type;
  _x_dir_type x_dir;

   typedef double _y_dir_type;
  _y_dir_type y_dir;




  typedef boost::shared_ptr< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleUavCmd_

typedef ::uav_msgs::SimpleUavCmd_<std::allocator<void> > SimpleUavCmd;

typedef boost::shared_ptr< ::uav_msgs::SimpleUavCmd > SimpleUavCmdPtr;
typedef boost::shared_ptr< ::uav_msgs::SimpleUavCmd const> SimpleUavCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::SimpleUavCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'uav_msgs': ['/home/sam/Desktop/pixhawk/src/uav-msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2741821bd04de0c5c67cb85abe3316c6";
  }

  static const char* value(const ::uav_msgs::SimpleUavCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2741821bd04de0c5ULL;
  static const uint64_t static_value2 = 0xc67cb85abe3316c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/SimpleUavCmd";
  }

  static const char* value(const ::uav_msgs::SimpleUavCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SimpleUavCmd.msg\n\
# Message describing single UAV command for roomba following\n\
\n\
# Timestamp when issued\n\
# time timestamp\n\
\n\
# Suggested Moving Direction\n\
float64 x_dir\n\
float64 y_dir\n\
";
  }

  static const char* value(const ::uav_msgs::SimpleUavCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_dir);
      stream.next(m.y_dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SimpleUavCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::SimpleUavCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::SimpleUavCmd_<ContainerAllocator>& v)
  {
    s << indent << "x_dir: ";
    Printer<double>::stream(s, indent + "  ", v.x_dir);
    s << indent << "y_dir: ";
    Printer<double>::stream(s, indent + "  ", v.y_dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_SIMPLEUAVCMD_H
