"""autogenerated by genpy from uav_msgs/EstRoombaList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import uav_msgs.msg
import genpy

class EstRoombaList(genpy.Message):
  _md5sum = "21f683d31466b702adba7720f61ddf8c"
  _type = "uav_msgs/EstRoombaList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# RoombaEstList.msg
# Message containing list of tracked Roomba states

# Timestamp of state estimate
time timestamp

# Number of tracked roombas
int32 num_tracked

EstRoombaState[] roombas

================================================================================
MSG: uav_msgs/EstRoombaState
# RoombaEstState.msg
# Message describing estimated current state of a Roomba

# Timestamp of state estimate
time timestamp

# Roomba type specifier
int32 SHEEP=1
int32 OBSTACLE=5
int32 type

float64[] state
float64[] covariance

# State variable enumerations
int32 IDX_POS_X		= 0
int32 IDX_POS_Y		= 1
int32 IDX_BEARING	= 2

"""
  __slots__ = ['timestamp','num_tracked','roombas']
  _slot_types = ['time','int32','uav_msgs/EstRoombaState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,num_tracked,roombas

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EstRoombaList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.num_tracked is None:
        self.num_tracked = 0
      if self.roombas is None:
        self.roombas = []
    else:
      self.timestamp = genpy.Time()
      self.num_tracked = 0
      self.roombas = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.num_tracked))
      length = len(self.roombas)
      buff.write(_struct_I.pack(length))
      for val1 in self.roombas:
        _v1 = val1.timestamp
        _x = _v1
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
        buff.write(_struct_i.pack(val1.type))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.pack(pattern, *val1.state))
        length = len(val1.covariance)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.pack(pattern, *val1.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.roombas is None:
        self.roombas = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.num_tracked,) = _struct_2Ii.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.roombas = []
      for i in range(0, length):
        val1 = uav_msgs.msg.EstRoombaState()
        _v2 = val1.timestamp
        _x = _v2
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 4
        (val1.type,) = _struct_i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.state = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.covariance = struct.unpack(pattern, str[start:end])
        self.roombas.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.num_tracked))
      length = len(self.roombas)
      buff.write(_struct_I.pack(length))
      for val1 in self.roombas:
        _v3 = val1.timestamp
        _x = _v3
        buff.write(_struct_2I.pack(_x.secs, _x.nsecs))
        buff.write(_struct_i.pack(val1.type))
        length = len(val1.state)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.state.tostring())
        length = len(val1.covariance)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.roombas is None:
        self.roombas = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.num_tracked,) = _struct_2Ii.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.roombas = []
      for i in range(0, length):
        val1 = uav_msgs.msg.EstRoombaState()
        _v4 = val1.timestamp
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2I.unpack(str[start:end])
        start = end
        end += 4
        (val1.type,) = _struct_i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.state = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.roombas.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_2I = struct.Struct("<2I")
_struct_2Ii = struct.Struct("<2Ii")
