"""autogenerated by genpy from uav_msgs/GridIntersectList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import uav_msgs.msg
import genpy

class GridIntersectList(genpy.Message):
  _md5sum = "67be8c06c0088fe31e3d1ed40f95938b"
  _type = "uav_msgs/GridIntersectList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# GridIntersectList.msg
# Contains list of GridIntersectPoints

time timestamp
GridIntersectPoint[] points




================================================================================
MSG: uav_msgs/GridIntersectPoint
# GridIntersectPoint.msg
# Describes observed grid intersection point
# Produced by computer vision

# Corner -- identifies if this point is a corner
int32 corner
int32 NONE=0
int32 TOP_LEFT=1
int32 TOP_RIGHT=2
int32 BOTTOM_LEFT=3
int32 BOTTOM_RIGHT=4

# Position in UAV-centered body frame
float64 x
float64 y

"""
  __slots__ = ['timestamp','points']
  _slot_types = ['time','uav_msgs/GridIntersectPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,points

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GridIntersectList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.points is None:
        self.points = []
    else:
      self.timestamp = genpy.Time()
      self.points = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.timestamp.secs, _x.timestamp.nsecs))
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_struct_i2d.pack(_x.corner, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.points is None:
        self.points = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.timestamp.secs, _x.timestamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = uav_msgs.msg.GridIntersectPoint()
        _x = val1
        start = end
        end += 20
        (_x.corner, _x.x, _x.y,) = _struct_i2d.unpack(str[start:end])
        self.points.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.timestamp.secs, _x.timestamp.nsecs))
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1
        buff.write(_struct_i2d.pack(_x.corner, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.points is None:
        self.points = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.timestamp.secs, _x.timestamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = uav_msgs.msg.GridIntersectPoint()
        _x = val1
        start = end
        end += 20
        (_x.corner, _x.x, _x.y,) = _struct_i2d.unpack(str[start:end])
        self.points.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i2d = struct.Struct("<i2d")
_struct_2I = struct.Struct("<2I")
