"""autogenerated by genpy from uav_msgs/IMUSample.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class IMUSample(genpy.Message):
  _md5sum = "49095f1ca9bcbabb38765ebcac06e122"
  _type = "uav_msgs/IMUSample"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# IMUSample.msg
# IMU sensor data from single sample (assume all taken at same moment)

# Timestamp of measurement
time timestamp

# gyro data [rad/s]
float64 gyro_x
float64 gyro_y
float64 gyro_z

# acc data [m/s^2]
float64 acc_x
float64 acc_y
float64 acc_z

# mag data [T]
float64 mag_x
float64 mag_y
float64 mag_z

"""
  __slots__ = ['timestamp','gyro_x','gyro_y','gyro_z','acc_x','acc_y','acc_z','mag_x','mag_y','mag_z']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z,mag_x,mag_y,mag_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMUSample, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.gyro_x is None:
        self.gyro_x = 0.
      if self.gyro_y is None:
        self.gyro_y = 0.
      if self.gyro_z is None:
        self.gyro_z = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.mag_x is None:
        self.mag_x = 0.
      if self.mag_y is None:
        self.mag_y = 0.
      if self.mag_z is None:
        self.mag_z = 0.
    else:
      self.timestamp = genpy.Time()
      self.gyro_x = 0.
      self.gyro_y = 0.
      self.gyro_z = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.mag_x = 0.
      self.mag_y = 0.
      self.mag_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I9d.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.mag_x, _x.mag_y, _x.mag_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.mag_x, _x.mag_y, _x.mag_z,) = _struct_2I9d.unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I9d.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.mag_x, _x.mag_y, _x.mag_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.mag_x, _x.mag_y, _x.mag_z,) = _struct_2I9d.unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I9d = struct.Struct("<2I9d")
