"""autogenerated by genpy from uav_msgs/OptFlowSample.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class OptFlowSample(genpy.Message):
  _md5sum = "52f577ea00a26860ecfa6e22305b6b84"
  _type = "uav_msgs/OptFlowSample"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# OptFlowSample.msg
# Post-processed optical flow measurement

# Timestamp of measurement
time timestamp

# Integrated flow
uint32 integration_time_us	# integration period in us
float32 integrated_x
float32 integrated_y

# Integrated gyro roll rates for compensation
float32 integrated_xgyro
float32 integrated_ygyro
float32 integrated_zgyro

# Temperature
int32 temperature 		# *100 = degrees Celsius

# Quality
# scalar measure of flow quality [0,255]
# 255 => best quality
uint32 quality

# Ground distance [m]
float32 ground_distance
uint32 time_delta_distance_us	# us since distance measurement



"""
  __slots__ = ['timestamp','integration_time_us','integrated_x','integrated_y','integrated_xgyro','integrated_ygyro','integrated_zgyro','temperature','quality','ground_distance','time_delta_distance_us']
  _slot_types = ['time','uint32','float32','float32','float32','float32','float32','int32','uint32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,integration_time_us,integrated_x,integrated_y,integrated_xgyro,integrated_ygyro,integrated_zgyro,temperature,quality,ground_distance,time_delta_distance_us

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OptFlowSample, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.integration_time_us is None:
        self.integration_time_us = 0
      if self.integrated_x is None:
        self.integrated_x = 0.
      if self.integrated_y is None:
        self.integrated_y = 0.
      if self.integrated_xgyro is None:
        self.integrated_xgyro = 0.
      if self.integrated_ygyro is None:
        self.integrated_ygyro = 0.
      if self.integrated_zgyro is None:
        self.integrated_zgyro = 0.
      if self.temperature is None:
        self.temperature = 0
      if self.quality is None:
        self.quality = 0
      if self.ground_distance is None:
        self.ground_distance = 0.
      if self.time_delta_distance_us is None:
        self.time_delta_distance_us = 0
    else:
      self.timestamp = genpy.Time()
      self.integration_time_us = 0
      self.integrated_x = 0.
      self.integrated_y = 0.
      self.integrated_xgyro = 0.
      self.integrated_ygyro = 0.
      self.integrated_zgyro = 0.
      self.temperature = 0
      self.quality = 0
      self.ground_distance = 0.
      self.time_delta_distance_us = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I5fiIfI.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.integration_time_us, _x.integrated_x, _x.integrated_y, _x.integrated_xgyro, _x.integrated_ygyro, _x.integrated_zgyro, _x.temperature, _x.quality, _x.ground_distance, _x.time_delta_distance_us))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.integration_time_us, _x.integrated_x, _x.integrated_y, _x.integrated_xgyro, _x.integrated_ygyro, _x.integrated_zgyro, _x.temperature, _x.quality, _x.ground_distance, _x.time_delta_distance_us,) = _struct_3I5fiIfI.unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I5fiIfI.pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.integration_time_us, _x.integrated_x, _x.integrated_y, _x.integrated_xgyro, _x.integrated_ygyro, _x.integrated_zgyro, _x.temperature, _x.quality, _x.ground_distance, _x.time_delta_distance_us))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.integration_time_us, _x.integrated_x, _x.integrated_y, _x.integrated_xgyro, _x.integrated_ygyro, _x.integrated_zgyro, _x.temperature, _x.quality, _x.ground_distance, _x.time_delta_distance_us,) = _struct_3I5fiIfI.unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I5fiIfI = struct.Struct("<3I5fiIfI")
